openapi: 3.0.0
info:
  title: AdoptMe API - Pets
  version: 1.0.0
  description: Endpoints para gestionar mascotas

tags:
  - name: Pets
    description: Operaciones relacionadas con mascotas

paths:
  /api/pets:
    get:
      summary: Obtener todas las mascotas
      tags: [Pets]
      responses:
        '200':
          description: Lista de mascotas obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

    post:
      summary: Crear una nueva mascota
      tags: [Pets]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetInput'
      responses:
        '201':
          description: Mascota creada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Datos inválidos

  /api/pets/{pid}:
    get:
      summary: Obtener una mascota por ID
      tags: [Pets]
      parameters:
        - name: pid
          in: path
          required: true
          description: ID de la mascota
          schema:
            type: string
      responses:
        '200':
          description: Mascota encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Mascota no encontrada

    put:
      summary: Actualizar una mascota por ID
      tags: [Pets]
      parameters:
        - name: pid
          in: path
          required: true
          description: ID de la mascota
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetInput'
      responses:
        '200':
          description: Mascota actualizada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Datos inválidos
        '404':
          description: Mascota no encontrada

    delete:
      summary: Eliminar una mascota por ID
      tags: [Pets]
      parameters:
        - name: pid
          in: path
          required: true
          description: ID de la mascota
          schema:
            type: string
      responses:
        '200':
          description: Mascota eliminada correctamente
        '404':
          description: Mascota no encontrada

components:
  schemas:
    Pet:
      type: object
      properties:
        _id:
          type: string
          description: ID único de la mascota
        name:
          type: string
          description: Nombre de la mascota
        specie:
          type: string
          description: Especie de la mascota
        birthDate:
          type: string
          format: date
          description: Fecha de nacimiento
        adopted:
          type: boolean
          description: Indica si la mascota está adoptada
        owner:
          type: string
          nullable: true
          description: ID del dueño si fue adoptada
        image:
          type: string
          description: URL de la imagen de la mascota

    PetInput:
      type: object
      properties:
        name:
          type: string
        specie:
          type: string
        birthDate:
          type: string
          format: date
        image:
          type: string